### ISSUE TITLE
[✅Fixed] DEKM_dense.py error in REUTERS. loss:nan 

### ISSUE THREAD

**Issue by adelightday** [spdj2271/DeepKmeans#7] opened 2024-06-04 07:32 UTC
This was my result
<img width="1049" alt="Screenshot 2024-06-04 at 14 28 55" src="https://github.com/spdj2271/DEKM/assets/171264340/3e73d6ad-1ff8-4f1c-8093-3fc089359a79">

I tried to re-write the code as your solution from the previous issues as well but I still got loss:nan 
<img width="488" alt="Screenshot 2024-06-04 at 14 30 20" src="https://github.com/spdj2271/DEKM/assets/171264340/409b8e46-d3df-4de6-9757-991a4d97e97a">

Do you have solution for that? Thank you for considering my question!

**Comment by spdj2271** [comment] 2024-06-04 17:06
Thank you for your kind reminder. The issue was caused by a bug, which I have now fixed. Please refer to this [colab notebook](https://colab.research.google.com/drive/1L2HEDqsB_2ZsT2oxNxXj1GfIC72piTWj?usp=sharing#scrollTo=ONB35TMZCmoZ).
<img width="819" alt="图片" src="https://github.com/spdj2271/DEKM/assets/30624620/f9bbab94-1516-4543-a417-898d24ccb502">

To resolve this bug, you should comment out the [152-th line](https://github.com/spdj2271/DEKM/blob/d15eecec87ebd663fbad17c11ad38dc675120e47/DEKM_dense.py#L152) of code in DEKM_dense.py, which incorrectly sets the batch_size to 10000.

Thank you so much~

**Closed as completed** 2024-06-06 10:59 UTC
